# Generated by Django 4.1.2 on 2022-11-05 12:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0004_auctionlistings_watchlist_delete_auctionwatchlist'),
    ]

    operations = [
        migrations.RenameField(
            model_name='auctionlistings',
            old_name='start_bid',
            new_name='bid',
        ),
        migrations.RenameField(
            model_name='auctionlistings',
            old_name='user_id',
            new_name='seller',
        ),
        migrations.RemoveField(
            model_name='auctionbids',
            name='bid_price',
        ),
        migrations.RemoveField(
            model_name='auctionbids',
            name='bidder',
        ),
        migrations.RemoveField(
            model_name='auctionbids',
            name='listing_id',
        ),
        migrations.RemoveField(
            model_name='auctionbids',
            name='update_on',
        ),
        migrations.RemoveField(
            model_name='auctionlistings',
            name='watchlist',
        ),
        migrations.AlterField(
            model_name='auctionlistings',
            name='category',
            field=models.CharField(max_length=32),
        ),
        migrations.AlterField(
            model_name='auctionlistings',
            name='description',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.CreateModel(
            name='AuctionWatchlist',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('listings', models.ManyToManyField(blank=True, related_name='buy_later', to='auctions.auctionlistings')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='potiential_buiyer', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
