# Generated by Django 4.1.2 on 2022-11-05 13:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0005_rename_start_bid_auctionlistings_bid_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auctionwatchlist',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='potiential_buyer', to=settings.AUTH_USER_MODEL),
        ),
    ]
