# Generated by Django 4.1.2 on 2022-11-06 16:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0008_categories_alter_auctionlistings_category'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AuctionBids',
        ),
        migrations.AddField(
            model_name='auctioncomments',
            name='comment',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AddField(
            model_name='auctioncomments',
            name='user',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, related_name='reviewer', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='auctionlistings',
            name='comments',
            field=models.ManyToManyField(blank=True, related_name='review', to='auctions.auctioncomments'),
        ),
    ]
