# Generated by Django 4.1.2 on 2022-11-06 16:55

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0009_delete_auctionbids_auctioncomments_comment_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='auctionlistings',
            name='comments',
        ),
        migrations.AddField(
            model_name='auctioncomments',
            name='created_on',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='auctioncomments',
            name='listing',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='reviewer', to='auctions.auctionlistings'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='auctioncomments',
            name='comment',
            field=models.TextField(default=2),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='auctionlistings',
            name='created_on',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
