# Generated by Django 4.1.2 on 2022-11-06 18:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0011_rename_bid_auctionlistings_start_bid_auctionbids'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='auctionbids',
            name='lis',
        ),
        migrations.AddField(
            model_name='auctionbids',
            name='listing',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='list', to='auctions.auctionlistings'),
            preserve_default=False,
        ),
    ]
