# Generated by Django 4.1.2 on 2022-11-07 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0012_remove_auctionbids_lis_auctionbids_listing'),
    ]

    operations = [
        migrations.AddField(
            model_name='auctionlistings',
            name='bid_raise',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='auctionlistings',
            name='close',
            field=models.BooleanField(default=False),
        ),
    ]
