# Generated by Django 4.1.3 on 2022-11-15 08:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("network", "0008_remove_userfollowing_follow_userfollowing_follower_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="userfollowing",
            old_name="user",
            new_name="target",
        ),
    ]
