# Generated by Django 4.1.3 on 2022-11-15 09:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("network", "0009_rename_user_userfollowing_target"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userfollowing",
            name="target",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="target",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
