# Generated by Django 4.1.3 on 2022-11-15 11:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("network", "0011_alter_posts_user"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userfollowing",
            name="follower",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AlterField(
            model_name="userfollowing",
            name="target",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="follow",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
