# Generated by Django 4.1.3 on 2022-11-15 12:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("network", "0013_alter_userfollowing_follower"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userfollowing",
            name="follower",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL
            ),
        ),
    ]
