# Generated by Django 4.1.3 on 2022-11-17 06:48

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("network", "0015_alter_posts_user_alter_userfollowing_follower_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="posts",
            name="liker",
            field=models.ManyToManyField(
                blank=True, related_name="liked_post", to=settings.AUTH_USER_MODEL
            ),
        ),
    ]
