# Generated by Django 4.1.3 on 2022-11-17 06:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("network", "0016_posts_liker"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="posts",
            name="likes",
        ),
    ]
